/**********************************************************************
*Name：提供外部调用的返回值，
*Description：

======================================================
History                                                            
-------                                                            
	VERSION  AUTHOR          DATE            DETAIL                    
	1.0      lijun        2020-06-01         Created

***********************************************************************/ 
global  class IntfInboundResult 
{
    public Integer code;
    public String msg;
    public Object data;

   
}